/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginSE;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author lizir
 */
public class evaluacionDiagnostico extends javax.swing.JFrame {
 Statement st;
    PreparedStatement ps;
    ResultSet rs;
    conexionBD cBD = new conexionBD();
    Connection con = null;
    /**
     * Creates new form evaluacionDiagnostico
     */
    public evaluacionDiagnostico() {
        initComponents();
        this.txtUsuarios.setVisible(false);
        txtID.setBackground(new java.awt.Color(0,0,0,1));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        panelEvaluacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelDiagnostico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelTratamiento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fotoPaciente = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnGenerarPDF = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JLabel();
        barraLateral = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrarS = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btnCerrarS2 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        txtUsuarios = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        evaluaciones = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTecnicas = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAnalisis = new javax.swing.JTextArea();
        diagnostico = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        tratamiento = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTratamiento = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtID.setBorder(null);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 70, 50));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel13.setText("Código de paciente:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 50));

        panelEvaluacion.setBackground(new java.awt.Color(92, 155, 224));
        panelEvaluacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEvaluacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelEvaluacionMouseMoved(evt);
            }
        });
        panelEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEvaluacionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEvaluacionMouseExited(evt);
            }
        });
        panelEvaluacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Evaluaciones");
        panelEvaluacion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/datosgenerales icono (1).png"))); // NOI18N
        panelEvaluacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 50, 50));

        jPanel1.add(panelEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 360, 70));

        panelDiagnostico.setBackground(new java.awt.Color(92, 155, 224));
        panelDiagnostico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelDiagnostico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDiagnosticoMouseMoved(evt);
            }
        });
        panelDiagnostico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDiagnosticoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDiagnosticoMouseExited(evt);
            }
        });
        panelDiagnostico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Diagnóstico");
        panelDiagnostico.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/contacto icon.png"))); // NOI18N
        panelDiagnostico.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 50, 50));

        jPanel1.add(panelDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 360, 70));

        panelTratamiento.setBackground(new java.awt.Color(92, 155, 224));
        panelTratamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelTratamiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelTratamientoMouseMoved(evt);
            }
        });
        panelTratamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTratamientoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTratamientoMouseExited(evt);
            }
        });
        panelTratamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Tratamiento");
        panelTratamiento.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/consulta (1).png"))); // NOI18N
        panelTratamiento.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 50, 50));

        jPanel1.add(panelTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 360, 70));

        javax.swing.GroupLayout fotoPacienteLayout = new javax.swing.GroupLayout(fotoPaciente);
        fotoPaciente.setLayout(fotoPacienteLayout);
        fotoPacienteLayout.setHorizontalGroup(
            fotoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        fotoPacienteLayout.setVerticalGroup(
            fotoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(fotoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 230));

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        btnEliminar.setText("Limpiar campos");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 760, 160, 40));

        btnGenerarPDF.setBackground(new java.awt.Color(204, 255, 255));
        btnGenerarPDF.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        btnGenerarPDF.setText("Generar reporte en PDF");
        btnGenerarPDF.setBorder(null);
        btnGenerarPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 820, 230, 60));

        btnGuardar.setBackground(new java.awt.Color(153, 204, 255));
        btnGuardar.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        btnGuardar.setText("Guardar datos");
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 820, 200, 60));

        btnRegresar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/32170 (1).png"))); // NOI18N
        btnRegresar.setText("Regresar a Inicio");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        barraLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/degradado-difuminado-azul-7935.jpg"))); // NOI18N
        barraLateral.setText("jLabel1");
        jPanel1.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 900));

        jPanel2.setBackground(new java.awt.Color(229, 237, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/icon cerrar sesion.png"))); // NOI18N
        btnCerrarS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSMouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 50, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/SE png.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        logo.setIconTextGap(0);
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 100));

        btnCerrarS2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnCerrarS2.setText("Cerrar sesión");
        btnCerrarS2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarS2MouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrarS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, 30));

        lblBienvenido.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        lblBienvenido.setText("Evaluación y diagnóstico");
        jPanel2.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 110));

        txtUsuarios.setEditable(false);
        jPanel2.add(txtUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 1320, 100));

        evaluaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(161, 168, 214));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Evaluaciones del paciente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(901, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        evaluaciones.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        evaluaciones.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 40));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel14.setText("Observaciones generales de la conducta");
        evaluaciones.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        evaluaciones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 530, 220));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel15.setText("Análisis e interpretación de resultados");
        evaluaciones.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        txtTecnicas.setColumns(20);
        txtTecnicas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTecnicas.setRows(5);
        jScrollPane2.setViewportView(txtTecnicas);

        evaluaciones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 530, 220));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel16.setText("Técnicas psicológicas utilizadas");
        evaluaciones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtAnalisis.setColumns(20);
        txtAnalisis.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtAnalisis.setRows(5);
        jScrollPane3.setViewportView(txtAnalisis);

        evaluaciones.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 600, 530));

        jTabbedPane1.addTab("tab1", evaluaciones);

        diagnostico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        diagnostico.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 40));

        jPanel4.setBackground(new java.awt.Color(161, 168, 214));

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Diagnóstico general");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        diagnostico.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 50));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel17.setText("Diagnóstico final");
        diagnostico.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtDiagnostico.setRows(5);
        jScrollPane4.setViewportView(txtDiagnostico);

        diagnostico.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 1160, 520));

        jTabbedPane1.addTab("tab2", diagnostico);

        tratamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        tratamiento.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 40));

        jPanel8.setBackground(new java.awt.Color(161, 168, 214));

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tratamiento y plan de orientación");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tratamiento.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 50));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel18.setText("Tratamiento, plan y recomendaciones");
        tratamiento.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtTratamiento.setColumns(20);
        txtTratamiento.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTratamiento.setRows(5);
        jScrollPane5.setViewportView(txtTratamiento);

        tratamiento.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 1160, 520));

        jTabbedPane1.addTab("tab3", tratamiento);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 1280, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelEvaluacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEvaluacionMouseMoved
        panelEvaluacion.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_panelEvaluacionMouseMoved

    private void panelEvaluacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEvaluacionMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_panelEvaluacionMouseClicked

    private void panelEvaluacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEvaluacionMouseExited
        panelEvaluacion.setBackground(new Color(92,155,224));
    }//GEN-LAST:event_panelEvaluacionMouseExited

    private void panelDiagnosticoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDiagnosticoMouseMoved
        panelDiagnostico.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_panelDiagnosticoMouseMoved

    private void panelDiagnosticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDiagnosticoMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_panelDiagnosticoMouseClicked

    private void panelDiagnosticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDiagnosticoMouseExited
        panelDiagnostico.setBackground(new Color(92,155,224));
    }//GEN-LAST:event_panelDiagnosticoMouseExited

    private void panelTratamientoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTratamientoMouseMoved
        panelTratamiento.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_panelTratamientoMouseMoved

    private void panelTratamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTratamientoMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_panelTratamientoMouseClicked

    private void panelTratamientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTratamientoMouseExited
        panelTratamiento.setBackground(new Color(92,155,224));
    }//GEN-LAST:event_panelTratamientoMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        txtTecnicas.setText("");
        txtObservaciones.setText("");
        txtAnalisis.setText("");
        txtDiagnostico.setText("");
        txtTratamiento.setText("");
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        Document doc = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(doc, new FileOutputStream(ruta + "/OneDrive/Escritorio/Reporte_Paciente_" + txtID.getText() +".pdf"));
            doc.open();
            String identificador = txtID.getText();
            String sql = "SELECT * FROM datosgenerales WHERE id_paciente='"+identificador+"'";
            con = cBD.Conectar();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
            doc.addCreationDate();
            Paragraph parrafo = new Paragraph();
            
            parrafo.setFont(FontFactory.getFont("Roboto", 18, Font.BOLD, BaseColor.BLACK));
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("Datos del paciente\n\n");
            
            parrafo.setAlignment(Paragraph.ALIGN_LEFT);
            parrafo.setFont(FontFactory.getFont("Roboto", 14, BaseColor.BLACK));
            parrafo.add("Nombre: "+rs.getString("nombreP")+"\n");
            parrafo.add("Apellidos: "+rs.getString("apellidosP")+"\n");
            parrafo.add("Edad: "+rs.getString("edadP")+"\n");
            parrafo.add("Genero: "+rs.getString("generoP")+"\n");
            parrafo.add("Teléfono: "+rs.getString("tel")+"\n\n");
            parrafo.setFont(FontFactory.getFont("Roboto", 18, Font.BOLD, BaseColor.BLACK));
            parrafo.add("Diagnóstico y Tratamiento\n\n");
            parrafo.setFont(FontFactory.getFont("Roboto", 14, BaseColor.BLACK));
            parrafo.add("Diagnóstico final:\n"+txtDiagnostico.getText()+"\n");
            parrafo.add("Tratamiento y plan de orientación:\n"+txtTratamiento.getText()+"\n\n");
            parrafo.add(new Date().toString());
            doc.add(parrafo);
            
            
            doc.close();
            JOptionPane.showMessageDialog(null,"PDF creado correctamente. Revise su escritorio.");
            } 
        } catch(DocumentException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Error al crear PDF"+ e);
        } catch(SQLException e){
            
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
                             con = cBD.Conectar();
                             ps = con.prepareStatement("INSERT INTO evaluaciondiag (id_paciente, tecnicas, observaciones, analisis, diagnostico, tratamiento) VALUES(?,?,?,?,?,?)");
                             ps.setString(1, txtID.getText());
                             ps.setString(2, txtTecnicas.getText());
                             ps.setString(3, txtObservaciones.getText());
                             ps.setString(4, txtAnalisis.getText());
                             ps.setString(5, txtDiagnostico.getText());
                             ps.setString(6, txtTratamiento.getText());

                             int res = ps.executeUpdate();

                             if (res>0){
                                JOptionPane.showMessageDialog(null, "¡Éxito! Se han guardado los datos correctamente.");
                             } else {
                                 JOptionPane.showMessageDialog(null, "Ups. Ha sucedido un error.");
                             } 
                         } catch(Exception e){
                             System.err.println(e);
                         }
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed
   
    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        try {
            String sqlFoto = "SELECT email, fotoUsuario FROM usuarios WHERE usuario='"+txtUsuarios.getText()+"'";
            con = cBD.Conectar();
            st = con.createStatement();
            rs = st.executeQuery(sqlFoto);
            BufferedImage buffimg = null;
            byte[] image = null;
            while(rs.next()){
                image = rs.getBytes("fotoUsuario");
                InputStream img = rs.getBinaryStream(2);
                try {
                    this.btnRegresar.setEnabled(false);
                    this.setVisible(false);
                    new principalSE().setVisible(true);
                    principalSE.nombreUser.setText(txtUsuarios.getText());
                    String email = rs.getString("email");
                    principalSE.campoCorreo.setText(email);
                    buffimg = ImageIO.read(img);
                    fotoImagenMYSQL imagen = new fotoImagenMYSQL(principalSE.fotoUsuario.getHeight(), principalSE.fotoUsuario.getWidth(), buffimg);
                    principalSE.fotoUsuario.add(imagen);
                    principalSE.fotoUsuario.repaint();
                } catch(IOException ex){
                    System.err.println(ex.toString());
                }
            }
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnCerrarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSMouseClicked
        this.dispose();
        new loginInterfaz().setVisible(true);
    }//GEN-LAST:event_btnCerrarSMouseClicked

    private void btnCerrarS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarS2MouseClicked
        this.dispose();
        new loginInterfaz().setVisible(true);
    }//GEN-LAST:event_btnCerrarS2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(evaluacionDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(evaluacionDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(evaluacionDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(evaluacionDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new evaluacionDiagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraLateral;
    private javax.swing.JLabel btnCerrarS;
    private javax.swing.JLabel btnCerrarS2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JLabel btnRegresar;
    private javax.swing.JPanel diagnostico;
    private javax.swing.JPanel evaluaciones;
    public javax.swing.JPanel fotoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelDiagnostico;
    private javax.swing.JPanel panelEvaluacion;
    private javax.swing.JPanel panelTratamiento;
    public javax.swing.JPanel tratamiento;
    public javax.swing.JTextArea txtAnalisis;
    public javax.swing.JTextArea txtDiagnostico;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextArea txtObservaciones;
    public javax.swing.JTextArea txtTecnicas;
    public javax.swing.JTextArea txtTratamiento;
    public javax.swing.JTextField txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
