/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginSE;


import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author lizir
 */
public class loginInterfaz extends javax.swing.JFrame {
     
    /**
     * Creates new form loginInterfaz
     */
    public loginInterfaz() {
        initComponents();
        
        this.btnOcultar.setVisible(false);
    }
    

    public void Ingresar(){
        
        conexionBD cBD1 = new conexionBD();
        Connection con1 = null;
        PreparedStatement pst = null;
        ResultSet rss = null;
        String User = txtUsuario.getText();
        String Pass = txtContra.getText();
        if (User.equals("Ingresa tu nombre de usuario") || Pass.equals("password")){
            JOptionPane.showMessageDialog(this, "Uno o más campos están vacios. Favor de llenarlos");
        } else {
            try {
                con1 = cBD1.Conectar();
                pst = con1.prepareStatement("select * from usuarios where usuario='" + User
                        + "' and password ='" + Pass + "'");
                rss = pst.executeQuery();
                if(rss.next()){
                    try{
                    BufferedImage buffimg = null;
                    byte[] image = null;
                    image = rss.getBytes("fotoUsuario");
                    InputStream img = rss.getBinaryStream(5);
                    
                    this.setVisible(false);
                    principalSE pse = new principalSE();
                    pse.setVisible(true);
                    String nombre = rss.getString("usuario");
                    String correo = rss.getString("email");
                    principalSE.nombreUser.setText(nombre);
                    principalSE.campoCorreo.setText(correo);
                    
                    buffimg = ImageIO.read(img);
                    fotoImagenMYSQL imagen = new fotoImagenMYSQL(pse.fotoUsuario.getHeight(), pse.fotoUsuario.getWidth(), buffimg);
                    pse.fotoUsuario.add(imagen);
                    pse.fotoUsuario.repaint();
                    }catch(IOException ex){
                 System.err.println(ex.toString());
             }
                } else {
                    JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Vuelva a intentar de nuevo");
                }
                
            } catch (SQLException e){
                System.err.print(e.toString());
                JOptionPane.showMessageDialog(this,"Ocurrio un error inesperado.\n Favor comunicarse con el administrador.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();
        lblEncabezado = new javax.swing.JLabel();
        lblTituloInicio = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblContra = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtContra = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnOcultar = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        lblEncabezado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1015, 575));
        setResizable(false);

        bgLogin.setBackground(new java.awt.Color(255, 255, 255));
        bgLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/SE logo.png"))); // NOI18N
        bgLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 390, 510));

        lblBG.setBackground(new java.awt.Color(164, 193, 229));
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/bg login.png"))); // NOI18N
        bgLogin.add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 0, 450, 530));

        lblEncabezado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(102, 102, 102));
        lblEncabezado.setText("de padecimientos mentales");
        bgLogin.add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblTituloInicio.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblTituloInicio.setText("Iniciar Sesión");
        bgLogin.add(lblTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblUsuario.setText("Usuario");
        bgLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtUsuario.setForeground(java.awt.Color.gray);
        txtUsuario.setText("Ingresa tu nombre de usuario");
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setNextFocusableComponent(txtContra);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        bgLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 370, 40));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        bgLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 470, 10));

        lblContra.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblContra.setText("Contraseña");
        bgLogin.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        bgLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 470, 10));

        txtContra.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtContra.setForeground(new java.awt.Color(102, 102, 102));
        txtContra.setText("password");
        txtContra.setBorder(null);
        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraMousePressed(evt);
            }
        });
        bgLogin.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 370, 40));

        btnIngresar.setBackground(new java.awt.Color(1, 123, 226));
        btnIngresar.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        bgLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 170, 50));

        btnOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/ocultar_1.png"))); // NOI18N
        btnOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOcultarMouseClicked(evt);
            }
        });
        bgLogin.add(btnOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 40, 40));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/ver_1.png"))); // NOI18N
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        bgLogin.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 40, 40));

        lblEncabezado1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblEncabezado1.setForeground(new java.awt.Color(102, 102, 102));
        lblEncabezado1.setText("Sistema experto para evaluación y diagnóstico");
        bgLogin.add(lblEncabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        Ingresar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(txtUsuario.getText().equals("Ingresa tu nombre de usuario")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if(String.valueOf(txtContra.getPassword()).isEmpty()){
            txtContra.setText("password");
            txtContra.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMousePressed
        if(String.valueOf(txtContra.getPassword()).equals("password")){
            txtContra.setText("");
            txtContra.setForeground(Color.black);
        }
        if(txtUsuario.getText().isEmpty()){
            txtUsuario.setText("Ingresa tu nombre de usuario");
            txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtContraMousePressed

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        btnVer.setVisible(false);
        btnOcultar.setVisible(true);
        txtContra.setEchoChar((char)0);
    }//GEN-LAST:event_btnVerMouseClicked

    private void btnOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseClicked
        btnVer.setVisible(true);
        btnOcultar.setVisible(false);
        txtContra.setEchoChar('*');
    }//GEN-LAST:event_btnOcultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginInterfaz().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgLogin;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel btnOcultar;
    private javax.swing.JLabel btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblEncabezado1;
    private javax.swing.JLabel lblTituloInicio;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
