/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginSE;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lizir
 */
public class visualizarHistorial extends javax.swing.JFrame {
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    conexionBD cBD = new conexionBD();
    Connection con = null;
    PreparedStatement ps2;
    PreparedStatement ps3;
    PreparedStatement ps4;
    PreparedStatement ps5;
    ResultSet rs2;
    
    File fichero;
    public void seleccionarFoto(){
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.PNG","png","*JPG","jpg","*JPEG","jpeg");
        fc.setFileFilter(filtro);
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            fichero = fc.getSelectedFile();
            String ruta = fichero.getAbsolutePath();
            
            
            int x = fotoPaciente.getWidth();
            int y = fotoPaciente.getHeight();
            
            fotoImagen img = new fotoImagen(x,y,ruta);
            fotoPaciente.removeAll();
            fotoPaciente.add(img);
            fotoPaciente.repaint();      
        }
    }
    /**
     * Creates new form visualizarHistorial
     */
    public visualizarHistorial() {
        initComponents();
        txtUsuarios.setVisible(false);
        txtID.setVisible(false);
        btnGuardarCam.setVisible(false);
        btnCancelar.setVisible(false);
        subirFoto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        panelContactos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelHistorial = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelMotivo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fotoPaciente = new javax.swing.JPanel();
        subirFoto = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEvalu = new javax.swing.JButton();
        btnRegresar = new javax.swing.JLabel();
        barraLateral = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrarS = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btnCerrarS2 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtUsuarios = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        datosGenerales = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblNombreP = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        lblCalleyN = new javax.swing.JLabel();
        txtCalleyN = new javax.swing.JTextField();
        lblLugarN = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtLugarN = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        lblFechaN = new javax.swing.JLabel();
        txtFechaN = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblColonia = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        lblMunicipio = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        lblEstadoC = new javax.swing.JLabel();
        txtEstadoC = new javax.swing.JTextField();
        lblRFC = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        lblCURP = new javax.swing.JLabel();
        txtCURP = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        datosContacto = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblApellidos1 = new javax.swing.JLabel();
        txtApellidosF = new javax.swing.JTextField();
        lblGenero1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        lblNombreF = new javax.swing.JLabel();
        txtNombreF = new javax.swing.JTextField();
        lblCalleyN1 = new javax.swing.JLabel();
        txtCalleyNF = new javax.swing.JTextField();
        lblLugarN1 = new javax.swing.JLabel();
        txtEstadoF = new javax.swing.JTextField();
        txtLugarNF = new javax.swing.JTextField();
        lblEdad1 = new javax.swing.JLabel();
        txtEdadF = new javax.swing.JTextField();
        cbGeneroF = new javax.swing.JComboBox<>();
        lblFechaN1 = new javax.swing.JLabel();
        txtFechaNF = new javax.swing.JTextField();
        lblCorreo1 = new javax.swing.JLabel();
        txtCorreoF = new javax.swing.JTextField();
        lblColonia1 = new javax.swing.JLabel();
        txtColoniaF = new javax.swing.JTextField();
        lblMunicipio1 = new javax.swing.JLabel();
        txtMunicipioF = new javax.swing.JTextField();
        lblRFC1 = new javax.swing.JLabel();
        txtRFCF = new javax.swing.JTextField();
        lblCURP1 = new javax.swing.JLabel();
        txtCURPF = new javax.swing.JTextField();
        lblTel2 = new javax.swing.JLabel();
        txtTelF = new javax.swing.JTextField();
        motivos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblCambios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMotivo = new javax.swing.JTextArea();
        lblMotivo = new javax.swing.JLabel();
        cbCambios = new javax.swing.JComboBox<>();
        lblAlergia2 = new javax.swing.JLabel();
        cbDiscapacidad = new javax.swing.JComboBox<>();
        lblAnalisis = new javax.swing.JLabel();
        cbAnalisis = new javax.swing.JComboBox<>();
        lblDiscapacidad2 = new javax.swing.JLabel();
        txtDiscapacidad = new javax.swing.JTextField();
        lblAlergia = new javax.swing.JLabel();
        cbAlergia = new javax.swing.JComboBox<>();
        lblDiscapacidad = new javax.swing.JLabel();
        txtAlergia = new javax.swing.JTextField();
        historialFam = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblFamEC2 = new javax.swing.JLabel();
        cbFamConductas = new javax.swing.JComboBox<>();
        lblFamConsulta2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaFamEC = new javax.swing.JTextArea();
        lblFamPM = new javax.swing.JLabel();
        cbFamPM = new javax.swing.JComboBox<>();
        lblFamPM2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaFamPM = new javax.swing.JTextArea();
        lblFamEC = new javax.swing.JLabel();
        cbFamEC = new javax.swing.JComboBox<>();
        lblFamDaño = new javax.swing.JLabel();
        cbFamDaño = new javax.swing.JComboBox<>();
        lblFamConsulta = new javax.swing.JLabel();
        cbFamCP = new javax.swing.JComboBox<>();
        lblFamRelacion = new javax.swing.JLabel();
        cbFamRelacion = new javax.swing.JComboBox<>();
        btnGuardarCam = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContactos.setBackground(new java.awt.Color(92, 155, 224));
        panelContactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelContactos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelContactosMouseMoved(evt);
            }
        });
        panelContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelContactosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelContactosMouseExited(evt);
            }
        });
        panelContactos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Datos de contacto");
        panelContactos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/contacto icon.png"))); // NOI18N
        panelContactos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 50, 50));

        bgPanel.add(panelContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 360, 70));

        panelHistorial.setBackground(new java.awt.Color(92, 155, 224));
        panelHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelHistorial.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelHistorialMouseMoved(evt);
            }
        });
        panelHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHistorialMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHistorialMouseExited(evt);
            }
        });
        panelHistorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Historial familiar");
        panelHistorial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/historial.png"))); // NOI18N
        panelHistorial.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 50, 50));

        bgPanel.add(panelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 360, 70));

        panelDatos.setBackground(new java.awt.Color(92, 155, 224));
        panelDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelDatos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelDatosMouseMoved(evt);
            }
        });
        panelDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDatosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDatosMouseExited(evt);
            }
        });
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Datos generales");
        panelDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/datosgenerales icono (1).png"))); // NOI18N
        panelDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 50, 50));

        bgPanel.add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 360, 70));

        panelMotivo.setBackground(new java.awt.Color(92, 155, 224));
        panelMotivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMotivo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelMotivoMouseMoved(evt);
            }
        });
        panelMotivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMotivoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMotivoMouseExited(evt);
            }
        });
        panelMotivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Motivo consulta");
        panelMotivo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/consulta (1).png"))); // NOI18N
        panelMotivo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 50, 50));

        bgPanel.add(panelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 360, 70));

        subirFoto.setBackground(new java.awt.Color(204, 204, 204));
        subirFoto.setFont(new java.awt.Font("Roboto Black", 0, 15)); // NOI18N
        subirFoto.setLabel("Editar foto");
        subirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fotoPacienteLayout = new javax.swing.GroupLayout(fotoPaciente);
        fotoPaciente.setLayout(fotoPacienteLayout);
        fotoPacienteLayout.setHorizontalGroup(
            fotoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fotoPacienteLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(subirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        fotoPacienteLayout.setVerticalGroup(
            fotoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fotoPacienteLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(subirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        bgPanel.add(fotoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, 230));

        btnEditar.setBackground(new java.awt.Color(153, 204, 255));
        btnEditar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnEditar.setText("Editar historial");
        btnEditar.setBorder(null);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        bgPanel.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 170, 50));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        bgPanel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 170, 50));

        btnEvalu.setBackground(new java.awt.Color(153, 204, 255));
        btnEvalu.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnEvalu.setText("Evaluación y diagnóstico");
        btnEvalu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEvalu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEvaluMouseMoved(evt);
            }
        });
        btnEvalu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEvaluMouseExited(evt);
            }
        });
        btnEvalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluActionPerformed(evt);
            }
        });
        bgPanel.add(btnEvalu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 800, 240, 70));

        btnRegresar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/32170 (1).png"))); // NOI18N
        btnRegresar.setText("Regresar a Inicio");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        bgPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        barraLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/degradado-difuminado-azul-7935.jpg"))); // NOI18N
        barraLateral.setText("jLabel1");
        bgPanel.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 900));

        jPanel2.setBackground(new java.awt.Color(229, 237, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/icon cerrar sesion.png"))); // NOI18N
        btnCerrarS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSMouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 50, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSE/SE png.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        logo.setIconTextGap(0);
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 100));

        btnCerrarS2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnCerrarS2.setText("Cerrar sesión");
        btnCerrarS2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarS2MouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrarS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, 30));

        lblBienvenido.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        lblBienvenido.setText("Perfil clínico");
        jPanel2.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 110));

        txtID.setEditable(false);
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 280, -1));

        txtUsuarios.setEditable(false);
        jPanel2.add(txtUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 280, -1));

        bgPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 1320, 100));

        datosGenerales.setBackground(new java.awt.Color(245, 245, 245));
        datosGenerales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(161, 168, 214));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Datos generales del paciente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(901, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        datosGenerales.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        datosGenerales.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 40));

        lblApellidos.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblApellidos.setText("Apellidos");
        datosGenerales.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        txtApellidos.setEditable(false);
        txtApellidos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 330, 40));

        lblGenero.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblGenero.setText("Género");
        datosGenerales.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, -1, -1));

        lblEstado.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblEstado.setText("Estado de residencia");
        datosGenerales.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        lblNombreP.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblNombreP.setText("Nombre");
        datosGenerales.add(lblNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtNombreP.setEditable(false);
        txtNombreP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombreP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 330, 40));

        lblCalleyN.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCalleyN.setText("Calle y número");
        datosGenerales.add(lblCalleyN, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, -1, -1));

        txtCalleyN.setEditable(false);
        txtCalleyN.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCalleyN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtCalleyN, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 330, 40));

        lblLugarN.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblLugarN.setText("Lugar de nacimiento");
        datosGenerales.add(lblLugarN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        txtEstado.setEditable(false);
        txtEstado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 330, 40));

        txtLugarN.setEditable(false);
        txtLugarN.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtLugarN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtLugarN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 330, 40));

        lblEdad.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblEdad.setText("Edad");
        datosGenerales.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, -1, -1));

        txtEdad.setEditable(false);
        txtEdad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEdad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 120, 40));

        cbGenero.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "Hombre", "Otro" }));
        cbGenero.setBorder(null);
        cbGenero.setEnabled(false);
        datosGenerales.add(cbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 120, 40));

        lblFechaN.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFechaN.setText("Fecha de nacimiento");
        datosGenerales.add(lblFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txtFechaN.setEditable(false);
        txtFechaN.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtFechaN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 330, 40));

        lblCorreo.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCorreo.setText("Correo electrónico");
        datosGenerales.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, -1, -1));

        txtCorreo.setEditable(false);
        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 330, 40));

        lblColonia.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblColonia.setText("Colonia");
        datosGenerales.add(lblColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        txtColonia.setEditable(false);
        txtColonia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtColonia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 330, 40));

        lblMunicipio.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblMunicipio.setText("Municipio/localidad");
        datosGenerales.add(lblMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtMunicipio.setEditable(false);
        txtMunicipio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtMunicipio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 330, 40));

        lblEstadoC.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblEstadoC.setText("Estado Civil");
        datosGenerales.add(lblEstadoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        txtEstadoC.setEditable(false);
        txtEstadoC.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEstadoC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtEstadoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 330, 40));

        lblRFC.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblRFC.setText("RFC");
        datosGenerales.add(lblRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        txtRFC.setEditable(false);
        txtRFC.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRFC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 330, 40));

        lblCURP.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCURP.setText("CURP");
        datosGenerales.add(lblCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        txtCURP.setEditable(false);
        txtCURP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCURP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 330, 40));

        lblTel.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblTel.setText("Teléfono");
        datosGenerales.add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        txtTel.setEditable(false);
        txtTel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosGenerales.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 330, 40));

        jTabbedPane1.addTab("tab1", datosGenerales);

        datosContacto.setBackground(new java.awt.Color(245, 245, 245));
        datosContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        datosContacto.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 40));

        jPanel4.setBackground(new java.awt.Color(161, 168, 214));

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Datos de contacto familiar del paciente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        datosContacto.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 50));

        lblApellidos1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblApellidos1.setText("Apellidos del familiar");
        datosContacto.add(lblApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        txtApellidosF.setEditable(false);
        txtApellidosF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidosF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtApellidosF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 330, 40));

        lblGenero1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblGenero1.setText("Género");
        datosContacto.add(lblGenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, -1, -1));

        lblEstado1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblEstado1.setText("Estado de residencia");
        datosContacto.add(lblEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        lblNombreF.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblNombreF.setText("Nombre del familiar");
        datosContacto.add(lblNombreF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtNombreF.setEditable(false);
        txtNombreF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombreF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtNombreF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 330, 40));

        lblCalleyN1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCalleyN1.setText("Calle y número");
        datosContacto.add(lblCalleyN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, -1, -1));

        txtCalleyNF.setEditable(false);
        txtCalleyNF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCalleyNF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtCalleyNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 330, 40));

        lblLugarN1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblLugarN1.setText("Lugar de nacimiento");
        datosContacto.add(lblLugarN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        txtEstadoF.setEditable(false);
        txtEstadoF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEstadoF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtEstadoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 330, 40));

        txtLugarNF.setEditable(false);
        txtLugarNF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtLugarNF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtLugarNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 330, 40));

        lblEdad1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblEdad1.setText("Edad");
        datosContacto.add(lblEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, -1, -1));

        txtEdadF.setEditable(false);
        txtEdadF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEdadF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtEdadF, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 120, 40));

        cbGeneroF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbGeneroF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "Hombre", "Otro" }));
        cbGeneroF.setBorder(null);
        cbGeneroF.setEnabled(false);
        datosContacto.add(cbGeneroF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 120, 40));

        lblFechaN1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFechaN1.setText("Fecha de nacimiento");
        datosContacto.add(lblFechaN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txtFechaNF.setEditable(false);
        txtFechaNF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtFechaNF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtFechaNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 330, 40));

        lblCorreo1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCorreo1.setText("Correo electrónico del familiar");
        datosContacto.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, -1, -1));

        txtCorreoF.setEditable(false);
        txtCorreoF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCorreoF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtCorreoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 330, 40));

        lblColonia1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblColonia1.setText("Colonia");
        datosContacto.add(lblColonia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        txtColoniaF.setEditable(false);
        txtColoniaF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtColoniaF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtColoniaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 330, 40));

        lblMunicipio1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblMunicipio1.setText("Municipio/localidad");
        datosContacto.add(lblMunicipio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtMunicipioF.setEditable(false);
        txtMunicipioF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtMunicipioF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtMunicipioF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 330, 40));

        lblRFC1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblRFC1.setText("RFC(opcional)");
        datosContacto.add(lblRFC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        txtRFCF.setEditable(false);
        txtRFCF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRFCF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtRFCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 330, 40));

        lblCURP1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCURP1.setText("CURP (opcional)");
        datosContacto.add(lblCURP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        txtCURPF.setEditable(false);
        txtCURPF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCURPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtCURPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 330, 40));

        lblTel2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblTel2.setText("Teléfono del familiar");
        datosContacto.add(lblTel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        txtTelF.setEditable(false);
        txtTelF.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtTelF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        datosContacto.add(txtTelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 330, 40));

        jTabbedPane1.addTab("tab2", datosContacto);

        motivos.setBackground(new java.awt.Color(245, 245, 245));
        motivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        motivos.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 40));

        jPanel8.setBackground(new java.awt.Color(161, 168, 214));

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Motivo de consulta");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        motivos.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 50));

        lblCambios.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCambios.setText("Cambios inusuales en el cuerpo");
        motivos.add(lblCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        txtAreaMotivo.setEditable(false);
        txtAreaMotivo.setColumns(20);
        txtAreaMotivo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtAreaMotivo.setRows(5);
        txtAreaMotivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(txtAreaMotivo);

        motivos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 1160, 160));

        lblMotivo.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblMotivo.setText("Motivo de la consulta");
        motivos.add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        cbCambios.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        cbCambios.setEnabled(false);
        motivos.add(cbCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 230, 40));

        lblAlergia2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblAlergia2.setText("En caso de alergia de algún medicamento indicar");
        motivos.add(lblAlergia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        cbDiscapacidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbDiscapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        cbDiscapacidad.setEnabled(false);
        motivos.add(cbDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 230, 40));

        lblAnalisis.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblAnalisis.setText("Análisis de sangre los últimos 3 meses");
        motivos.add(lblAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        cbAnalisis.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbAnalisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        cbAnalisis.setEnabled(false);
        motivos.add(cbAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 230, 40));

        lblDiscapacidad2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblDiscapacidad2.setText("Indicar tipo de discapacidad en caso de tener");
        motivos.add(lblDiscapacidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, -1, -1));

        txtDiscapacidad.setEditable(false);
        txtDiscapacidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtDiscapacidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        motivos.add(txtDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 440, 40));

        lblAlergia.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblAlergia.setText("Alérgico a algún medicamento");
        motivos.add(lblAlergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        cbAlergia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbAlergia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        cbAlergia.setEnabled(false);
        motivos.add(cbAlergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 230, 40));

        lblDiscapacidad.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblDiscapacidad.setText("Discapacidad de algún tipo");
        motivos.add(lblDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        txtAlergia.setEditable(false);
        txtAlergia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtAlergia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        motivos.add(txtAlergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 440, 40));

        jTabbedPane1.addTab("tab3", motivos);

        historialFam.setBackground(new java.awt.Color(245, 245, 245));
        historialFam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        historialFam.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 40));

        jPanel10.setBackground(new java.awt.Color(161, 168, 214));

        jLabel12.setBackground(new java.awt.Color(153, 204, 255));
        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Historial clínico de familiares");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        historialFam.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1280, 50));

        lblFamEC2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamEC2.setText("Si es así, indicar los padecimientos");
        historialFam.add(lblFamEC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        cbFamConductas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbFamConductas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No", "Indefinido" }));
        cbFamConductas.setEnabled(false);
        historialFam.add(cbFamConductas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 310, 50));

        lblFamConsulta2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamConsulta2.setText("Familiares con conductas agresivas y/o indiferentes");
        historialFam.add(lblFamConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        txtAreaFamEC.setEditable(false);
        txtAreaFamEC.setColumns(20);
        txtAreaFamEC.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtAreaFamEC.setRows(5);
        jScrollPane2.setViewportView(txtAreaFamEC);

        historialFam.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 570, 100));

        lblFamPM.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamPM.setText("Ha tenido familiares con padecimientos mentales");
        historialFam.add(lblFamPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        cbFamPM.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbFamPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No", "Indefinido" }));
        cbFamPM.setEnabled(false);
        historialFam.add(cbFamPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 310, 50));

        lblFamPM2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamPM2.setText("Si es así, indicar los padecimientos");
        historialFam.add(lblFamPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        txtAreaFamPM.setEditable(false);
        txtAreaFamPM.setColumns(20);
        txtAreaFamPM.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtAreaFamPM.setRows(5);
        jScrollPane3.setViewportView(txtAreaFamPM);

        historialFam.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 570, 100));

        lblFamEC.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamEC.setText("Ha tenido familiares con enfermedades crónicas");
        historialFam.add(lblFamEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        cbFamEC.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbFamEC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No", "Indefinido" }));
        cbFamEC.setEnabled(false);
        historialFam.add(cbFamEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 310, 50));

        lblFamDaño.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamDaño.setText("Familiares le han dañado físicamente y/o emocionalmente");
        historialFam.add(lblFamDaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        cbFamDaño.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbFamDaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No", "Indefinido" }));
        cbFamDaño.setEnabled(false);
        historialFam.add(cbFamDaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 310, 50));

        lblFamConsulta.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamConsulta.setText("Familiares han consultado alguna vez psicólogo");
        historialFam.add(lblFamConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        cbFamCP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbFamCP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No", "Indefinido" }));
        cbFamCP.setEnabled(false);
        historialFam.add(cbFamCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 310, 50));

        lblFamRelacion.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblFamRelacion.setText("Tiene buena relación con sus familiares");
        historialFam.add(lblFamRelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        cbFamRelacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbFamRelacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "Regular", "No", "Indefinido" }));
        cbFamRelacion.setEnabled(false);
        historialFam.add(cbFamRelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 310, 50));

        jTabbedPane1.addTab("tab4", historialFam);

        bgPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 1280, 740));

        btnGuardarCam.setBackground(new java.awt.Color(153, 204, 255));
        btnGuardarCam.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnGuardarCam.setText("Guardar cambios");
        btnGuardarCam.setBorder(null);
        btnGuardarCam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCamActionPerformed(evt);
            }
        });
        bgPanel.add(btnGuardarCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 820, 220, 60));

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar perfil clínico");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bgPanel.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 820, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
            try {
            String sqlFoto = "SELECT email, fotoUsuario FROM usuarios WHERE usuario='"+txtUsuarios.getText()+"'";
            con = cBD.Conectar();
            st = con.createStatement();
            rs = st.executeQuery(sqlFoto);
            BufferedImage buffimg = null;
            byte[] image = null;
            while(rs.next()){
                image = rs.getBytes("fotoUsuario");
             InputStream img = rs.getBinaryStream(2);
             try {
                    this.btnRegresar.setEnabled(false);
                    this.setVisible(false);
                    new principalSE().setVisible(true);
                    principalSE.nombreUser.setText(txtUsuarios.getText());
                    String email = rs.getString("email");
                    principalSE.campoCorreo.setText(email);
                 buffimg = ImageIO.read(img);
                 fotoImagenMYSQL imagen = new fotoImagenMYSQL(principalSE.fotoUsuario.getHeight(), principalSE.fotoUsuario.getWidth(), buffimg);
                 principalSE.fotoUsuario.add(imagen);
                 principalSE.fotoUsuario.repaint();
             } catch(IOException ex){
                 System.err.println(ex.toString());
             }
            }
        }catch (Exception e){
            System.err.println(e);  
        }
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnCerrarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSMouseClicked
        this.dispose();
        new loginInterfaz().setVisible(true);
    }//GEN-LAST:event_btnCerrarSMouseClicked

    private void btnCerrarS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarS2MouseClicked
        this.dispose();
        new loginInterfaz().setVisible(true);
    }//GEN-LAST:event_btnCerrarS2MouseClicked

    private void panelDatosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDatosMouseMoved
        panelDatos.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_panelDatosMouseMoved

    private void panelDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDatosMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_panelDatosMouseClicked

    private void panelDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDatosMouseExited
        panelDatos.setBackground(new Color(92,155,224));
    }//GEN-LAST:event_panelDatosMouseExited

    private void panelContactosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContactosMouseMoved
        panelContactos.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_panelContactosMouseMoved

    private void panelContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContactosMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_panelContactosMouseClicked

    private void panelContactosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContactosMouseExited
        panelContactos.setBackground(new Color(92,155,224));
    }//GEN-LAST:event_panelContactosMouseExited

    private void panelMotivoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMotivoMouseMoved
        panelMotivo.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_panelMotivoMouseMoved

    private void panelMotivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMotivoMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_panelMotivoMouseClicked

    private void panelMotivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMotivoMouseExited
        panelMotivo.setBackground(new Color(92,155,224));
    }//GEN-LAST:event_panelMotivoMouseExited

    private void panelHistorialMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHistorialMouseMoved
        panelHistorial.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_panelHistorialMouseMoved

    private void panelHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHistorialMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_panelHistorialMouseClicked

    private void panelHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHistorialMouseExited
        panelHistorial.setBackground(new Color(92,155,224));
    }//GEN-LAST:event_panelHistorialMouseExited

    private void btnEvaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluActionPerformed
     evaluacionDiagnostico ed = new evaluacionDiagnostico();
        try {
            String sqlFoto = "SELECT id_paciente, foto FROM datosgenerales WHERE id_paciente='"+txtID.getText()+"'";
            con = cBD.Conectar();
            st = con.createStatement();
            rs = st.executeQuery(sqlFoto);
            BufferedImage buffimg = null;
            byte[] image = null;
            while(rs.next()){
                image = rs.getBytes("foto");
             InputStream img = rs.getBinaryStream(2);
             try {
                    this.setVisible(false);
                    
                    ed.setVisible(true);
                    String idPaciente = txtID.getText();
                    ed.txtID.setText(idPaciente);
                    String userDoc = txtUsuarios.getText();
                    ed.txtUsuarios.setText(userDoc);
                 buffimg = ImageIO.read(img);
                 fotoImagenMYSQL imagen = new fotoImagenMYSQL(ed.fotoPaciente.getHeight(), ed.fotoPaciente.getWidth(), buffimg);
                 ed.fotoPaciente.add(imagen);
                 ed.fotoPaciente.repaint();
             } catch(IOException ex){
                 System.err.println(ex.toString());
             }
            }
        }catch (Exception e){
            System.err.println(e);  
        }
  
        try{
            String sql2 = "SELECT * FROM evaluaciondiag WHERE id_paciente='"+txtID.getText()+"'";
            con = cBD.Conectar();
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            while(rs.next()){
                ed.txtTecnicas.setText(rs.getString("tecnicas"));
                ed.txtObservaciones.setText(rs.getString("observaciones"));
                ed.txtAnalisis.setText(rs.getString("analisis"));
                ed.txtDiagnostico.setText(rs.getString("diagnostico"));
                ed.txtTratamiento.setText(rs.getString("tratamiento"));
            } 
        }catch (SQLException e){
                    
                    }
    }//GEN-LAST:event_btnEvaluActionPerformed

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
        btnEditar.setBackground(new Color(229,237,246));
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        btnEditar.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEvaluMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluMouseMoved
        btnEvalu.setBackground(new Color(229,237,246));
    }//GEN-LAST:event_btnEvaluMouseMoved

    private void btnEvaluMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluMouseExited
        btnEvalu.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnEvaluMouseExited

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnEditar.setVisible(false);
        btnCancelar.setVisible(true);
        btnEliminar.setVisible(false);
        btnGuardarCam.setVisible(true);
        subirFoto.setVisible(true);
        
        txtNombreP.setEditable(true);
        txtApellidos.setEditable(true);
        txtEdad.setEditable(true);
        cbGenero.setEnabled(true);
        txtFechaN.setEditable(true);
        txtLugarN.setEditable(true);
        txtEstado.setEditable(true);
        txtMunicipio.setEditable(true);
        txtColonia.setEditable(true);
        txtCalleyN.setEditable(true);
        txtCURP.setEditable(true);
        txtRFC.setEditable(true);
        txtCorreo.setEditable(true);
        txtTel.setEditable(true);
        txtEstadoC.setEditable(true);
        
        txtNombreF.setEditable(true);
        txtApellidosF.setEditable(true);
        txtEdadF.setEditable(true);
        cbGeneroF.setEnabled(true);
        txtFechaNF.setEditable(true);
        txtLugarNF.setEditable(true);
        txtEstadoF.setEditable(true);
        txtMunicipioF.setEditable(true);
        txtColoniaF.setEditable(true);
        txtCalleyNF.setEditable(true);
        txtCURPF.setEditable(true);
        txtRFCF.setEditable(true);
        txtCorreoF.setEditable(true);
        txtTelF.setEditable(true);
        
        txtAreaMotivo.setEditable(true);
        cbAnalisis.setEnabled(true);
        cbCambios.setEnabled(true);
        cbAlergia.setEnabled(true);
        txtAlergia.setEditable(true);
        cbDiscapacidad.setEnabled(true);
        txtDiscapacidad.setEditable(true);
        
        cbFamPM.setEnabled(true);
        txtAreaFamPM.setEditable(true);
        cbFamEC.setEnabled(true);
        txtAreaFamEC.setEditable(true);
        cbFamCP.setEnabled(true);
        cbFamConductas.setEnabled(true);
        cbFamRelacion.setEnabled(true);
        cbFamDaño.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCamActionPerformed
        
        try {
            con = cBD.Conectar();
            ps = con.prepareStatement("UPDATE datosgenerales SET usuarioDoctor=?, apellidosP=?, nombreP=?, edadP=?, generoP=?, fechaNac=?, "
                    + "lugarNac=?, estadoResi=?, municipio=?, colonia=?, calleNum=?, CURP=?, RFC=?, email=?, tel=?, estadoCivil=?, foto=? "
                    + "WHERE id_paciente ='" +txtID.getText()+ "'");
            ps.setString(1, txtUsuarios.getText());
            ps.setString(2, txtApellidos.getText());
            ps.setString(3, txtNombreP.getText());
            ps.setString(4, txtEdad.getText());
            ps.setString(5, cbGenero.getSelectedItem().toString());
            ps.setString(6, txtFechaN.getText());
            ps.setString(7, txtLugarN.getText());
            ps.setString(8, txtEstado.getText());
            ps.setString(9, txtMunicipio.getText());
            ps.setString(10, txtColonia.getText());
            ps.setString(11, txtCalleyN.getText());
            ps.setString(12, txtCURP.getText());
            ps.setString(13, txtRFC.getText());
            ps.setString(14, txtCorreo.getText());
            ps.setString(15, txtTel.getText());
            ps.setString(16, txtEstadoC.getText());
            FileInputStream fis = new FileInputStream(fichero);
            ps.setBinaryStream(17, fis, (int) fichero.length());
            
            
            ps2 = con.prepareStatement("UPDATE datoscontacto SET nombreF=?, apellidosF=?, edadF=?, generoF=?, fechaNacF=?, "
                    + "lugarNacF=?, estadoResiF=?, municipioF=?, coloniaF=?, calleNumF=?, CURPfam=?, RFCfam=?, emailFam=?, telFam=?"
                    + "WHERE id_paciente ='" +txtID.getText()+ "'");
            ps2.setString(1, txtNombreF.getText());
            ps2.setString(2, txtApellidosF.getText());
            ps2.setString(3, txtEdadF.getText());
            ps2.setString(4, cbGeneroF.getSelectedItem().toString());
            ps2.setString(5, txtFechaNF.getText());
            ps2.setString(6, txtLugarNF.getText());
            ps2.setString(7, txtEstadoF.getText());
            ps2.setString(8, txtMunicipioF.getText());
            ps2.setString(9, txtColoniaF.getText());
            ps2.setString(10, txtCalleyNF.getText());
            ps2.setString(11, txtCURPF.getText());
            ps2.setString(12, txtRFCF.getText());
            ps2.setString(13, txtCorreoF.getText());
            ps2.setString(14, txtTelF.getText());
            
            ps3 = con.prepareStatement("UPDATE motivoconsulta SET motivo=?, analisisSangre=?, cambios=?, alergias=?, medAlergia=?, discapacidad=?, tipoDis=? WHERE id_paciente ='" +txtID.getText()+ "'");
            ps3.setString(1, txtAreaMotivo.getText());
            ps3.setString(2, cbAnalisis.getSelectedItem().toString());
            ps3.setString(3, cbCambios.getSelectedItem().toString());
            ps3.setString(4, cbAlergia.getSelectedItem().toString());
            ps3.setString(5, txtAlergia.getText());
            ps3.setString(6, cbDiscapacidad.getSelectedItem().toString());
            ps3.setString(7, txtDiscapacidad.getText());
            
            ps4 = con.prepareStatement("UPDATE historialfamiliar SET famPM=?, famPMdes=?, famEC=?, famECdes=?, famPsico=?, famConductas=?, famRelacion=?, famMaltrato=? WHERE id_paciente ='" +txtID.getText()+ "'");
            ps4.setString(1, cbFamPM.getSelectedItem().toString());
            ps4.setString(2, txtAreaFamPM.getText());
            ps4.setString(3, cbFamEC.getSelectedItem().toString());
            ps4.setString(4, txtAreaFamEC.getText());
            ps4.setString(5, cbFamCP.getSelectedItem().toString());
            ps4.setString(6, cbFamConductas.getSelectedItem().toString());
            ps4.setString(7, cbFamRelacion.getSelectedItem().toString());
            ps4.setString(8, cbFamDaño.getSelectedItem().toString());
            
            int res = ps.executeUpdate();
            int res2 = ps2.executeUpdate();
            int res3 = ps3.executeUpdate();
            int res4 = ps4.executeUpdate();
            if (res>0 || res2>0 || res3>0 || res4>0){
                JOptionPane.showMessageDialog(null, "¡Éxito! Se han guardado los cambios correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Ups. Ha sucedido un error.");
            }
        } catch(Exception e){
            System.err.println(e);
        }
        
        btnEditar.setEnabled(true);
        btnGuardarCam.setVisible(false);
        btnEliminar.setVisible(true);
        subirFoto.setVisible(false);
        deshabilitartxt();
    }//GEN-LAST:event_btnGuardarCamActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCancelar.setVisible(false);
        btnEditar.setVisible(true);
        btnGuardarCam.setVisible(false);
        btnEliminar.setVisible(true);
        subirFoto.setVisible(false);
        deshabilitartxt();
       
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int pregunta =  JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas eliminar este perfil?",
                "Mensaje", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        System.out.print(pregunta);
        if(pregunta==0){
            try {
            con = cBD.Conectar();
            ps = con.prepareStatement("DELETE from datosgenerales WHERE id_paciente ='" +txtID.getText()+ "'");
            ps2 = con.prepareStatement("DELETE from datoscontacto WHERE id_paciente ='" +txtID.getText()+ "'");
            ps3 = con.prepareStatement("DELETE from motivoconsulta WHERE id_paciente ='" +txtID.getText()+ "'");
            ps4 = con.prepareStatement("DELETE from historialfamiliar WHERE id_paciente ='" +txtID.getText()+ "'");
            ps5 = con.prepareStatement("DELETE from evaluaciondiag WHERE id_paciente ='" +txtID.getText()+ "'");
            int res = ps.executeUpdate();
            int res2 = ps2.executeUpdate();
            int res3 = ps3.executeUpdate();
            int res4 = ps4.executeUpdate();
            int res5 = ps5.executeUpdate();
            if (res>0 || res2>0 || res3>0 || res4>0 || res5>0){
                JOptionPane.showMessageDialog(null, "Se ha eliminado el perfil correctamente.");
                            try {
                        String sqlFoto = "SELECT email, fotoUsuario FROM usuarios WHERE usuario='"+txtUsuarios.getText()+"'";
                        con = cBD.Conectar();
                        st = con.createStatement();
                        rs = st.executeQuery(sqlFoto);
                        BufferedImage buffimg = null;
                        byte[] image = null;
                        while(rs.next()){
                            image = rs.getBytes("fotoUsuario");
                         InputStream img = rs.getBinaryStream(2);
                         try {
                                this.btnRegresar.setEnabled(false);
                                this.setVisible(false);
                                new principalSE().setVisible(true);
                                principalSE.nombreUser.setText(txtUsuarios.getText());
                                String email = rs.getString("email");
                                principalSE.campoCorreo.setText(email);
                             buffimg = ImageIO.read(img);
                             fotoImagenMYSQL imagen = new fotoImagenMYSQL(principalSE.fotoUsuario.getHeight(), principalSE.fotoUsuario.getWidth(), buffimg);
                             principalSE.fotoUsuario.add(imagen);
                             principalSE.fotoUsuario.repaint();
                         } catch(IOException ex){
                             System.err.println(ex.toString());
                         }
                        }
                    }catch (Exception e){
                        System.err.println(e);  
                    }
            } else {
                JOptionPane.showMessageDialog(null, "Ups. Ha sucedido un error.");
            }
        } catch(Exception e){
            System.err.println(e);
        }
        } 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void subirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirFotoActionPerformed
           seleccionarFoto();
    }//GEN-LAST:event_subirFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizarHistorial().setVisible(true);
            }
        });
    }
    public void deshabilitartxt(){
        txtNombreP.setEditable(false);
        txtApellidos.setEditable(false);
        txtEdad.setEditable(false);
        cbGenero.setEnabled(false);
        txtFechaN.setEditable(false);
        txtLugarN.setEditable(false);
        txtEstado.setEditable(false);
        txtMunicipio.setEditable(false);
        txtColonia.setEditable(false);
        txtCalleyN.setEditable(false);
        txtCURP.setEditable(false);
        txtRFC.setEditable(false);
        txtCorreo.setEditable(false);
        txtTel.setEditable(false);
        txtEstadoC.setEditable(false);
        
        txtNombreF.setEditable(false);
        txtApellidosF.setEditable(false);
        txtEdadF.setEditable(false);
        cbGeneroF.setEnabled(false);
        txtFechaNF.setEditable(false);
        txtLugarNF.setEditable(false);
        txtEstadoF.setEditable(false);
        txtMunicipioF.setEditable(false);
        txtColoniaF.setEditable(false);
        txtCalleyNF.setEditable(false);
        txtCURPF.setEditable(false);
        txtRFCF.setEditable(false);
        txtCorreoF.setEditable(false);
        txtTelF.setEditable(false);
        
        txtAreaMotivo.setEditable(false);
        cbAnalisis.setEnabled(false);
        cbCambios.setEnabled(false);
        cbAlergia.setEnabled(false);
        txtAlergia.setEditable(false);
        cbDiscapacidad.setEnabled(false);
        txtDiscapacidad.setEditable(false);
        
        cbFamPM.setEnabled(false);
        txtAreaFamPM.setEditable(false);
        cbFamEC.setEnabled(false);
        txtAreaFamEC.setEditable(false);
        cbFamCP.setEnabled(false);
        cbFamConductas.setEnabled(false);
        cbFamRelacion.setEnabled(false);
        cbFamDaño.setEnabled(false);

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraLateral;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCerrarS;
    private javax.swing.JLabel btnCerrarS2;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEvalu;
    private javax.swing.JButton btnGuardarCam;
    public javax.swing.JLabel btnRegresar;
    public javax.swing.JComboBox<String> cbAlergia;
    public javax.swing.JComboBox<String> cbAnalisis;
    public javax.swing.JComboBox<String> cbCambios;
    public javax.swing.JComboBox<String> cbDiscapacidad;
    public javax.swing.JComboBox<String> cbFamCP;
    public javax.swing.JComboBox<String> cbFamConductas;
    public javax.swing.JComboBox<String> cbFamDaño;
    public javax.swing.JComboBox<String> cbFamEC;
    public javax.swing.JComboBox<String> cbFamPM;
    public javax.swing.JComboBox<String> cbFamRelacion;
    public javax.swing.JComboBox<String> cbGenero;
    public javax.swing.JComboBox<String> cbGeneroF;
    private javax.swing.JPanel datosContacto;
    private javax.swing.JPanel datosGenerales;
    public javax.swing.JPanel fotoPaciente;
    private javax.swing.JPanel historialFam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAlergia;
    private javax.swing.JLabel lblAlergia2;
    private javax.swing.JLabel lblAnalisis;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidos1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCURP;
    private javax.swing.JLabel lblCURP1;
    private javax.swing.JLabel lblCalleyN;
    private javax.swing.JLabel lblCalleyN1;
    private javax.swing.JLabel lblCambios;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblColonia1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblDiscapacidad;
    private javax.swing.JLabel lblDiscapacidad2;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdad1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstadoC;
    private javax.swing.JLabel lblFamConsulta;
    private javax.swing.JLabel lblFamConsulta2;
    private javax.swing.JLabel lblFamDaño;
    private javax.swing.JLabel lblFamEC;
    private javax.swing.JLabel lblFamEC2;
    private javax.swing.JLabel lblFamPM;
    private javax.swing.JLabel lblFamPM2;
    private javax.swing.JLabel lblFamRelacion;
    private javax.swing.JLabel lblFechaN;
    private javax.swing.JLabel lblFechaN1;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGenero1;
    private javax.swing.JLabel lblLugarN;
    private javax.swing.JLabel lblLugarN1;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblMunicipio1;
    private javax.swing.JLabel lblNombreF;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblRFC;
    private javax.swing.JLabel lblRFC1;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTel2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel motivos;
    private javax.swing.JPanel panelContactos;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JPanel panelMotivo;
    private javax.swing.JButton subirFoto;
    public javax.swing.JTextField txtAlergia;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtApellidosF;
    public javax.swing.JTextArea txtAreaFamEC;
    public javax.swing.JTextArea txtAreaFamPM;
    public javax.swing.JTextArea txtAreaMotivo;
    public javax.swing.JTextField txtCURP;
    public javax.swing.JTextField txtCURPF;
    public javax.swing.JTextField txtCalleyN;
    public javax.swing.JTextField txtCalleyNF;
    public javax.swing.JTextField txtColonia;
    public javax.swing.JTextField txtColoniaF;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtCorreoF;
    public javax.swing.JTextField txtDiscapacidad;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtEdadF;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtEstadoC;
    public javax.swing.JTextField txtEstadoF;
    public javax.swing.JTextField txtFechaN;
    public javax.swing.JTextField txtFechaNF;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtLugarN;
    public javax.swing.JTextField txtLugarNF;
    public javax.swing.JTextField txtMunicipio;
    public javax.swing.JTextField txtMunicipioF;
    public javax.swing.JTextField txtNombreF;
    public javax.swing.JTextField txtNombreP;
    public javax.swing.JTextField txtRFC;
    public javax.swing.JTextField txtRFCF;
    public javax.swing.JTextField txtTel;
    public javax.swing.JTextField txtTelF;
    public javax.swing.JTextField txtUsuarios;
    // End of variables declaration//GEN-END:variables

   
}
